import { SponsorType } from "../types/sponsorTypes";

export const mockSponsors: SponsorType[] = [
	{
		idSponsor: "1",
		nombre: "Antamina",
		image: "/img/Antamina_logo.png",
    prefijoIdioma: "SP",
		descripcionIdioma: "ESPAÑOL",
		url: "https://www.antamina.com/",
		categoria: "socio estratégico",
	},
	{
		idSponsor: "2",
		nombre: "Repsol",
		image: "/img/1614272675repsol.png",
    prefijoIdioma: "SP",
		descripcionIdioma: "ESPAÑOL",
		url: "https://www.repsol.com/es/index.cshtml",
		categoria:  "oro",
	},
	{
		idSponsor: "3",
		nombre: "Claro",
		image: "/img/Claro_logo3.png",
    prefijoIdioma: "SP",
		descripcionIdioma: "ESPAÑOL",
		url: "hhttps://www.claro.com.pe/empresas/",
		categoria: "cobre",
	},
	{
		idSponsor: "4",
		nombre: "BHP",
		image: "/img/BHP_Logo.png",
    prefijoIdioma: "SP",
		descripcionIdioma: "ESPAÑOL",
		url: "https://www.bhp.com/",
		categoria: "colaborador",
	},
	{
		idSponsor: "5",
		nombre: "KALLPA",
		image: "/img/KALLPA_Logo.png",
    prefijoIdioma: "SP",
		descripcionIdioma: "ESPAÑOL",
		url: "https://kallpageneracion.com.pe/en/",
		categoria: "agradecimiento",
	},
	{
		idSponsor: "6",
		nombre: "LATAM airlines",
		image: "/img/Latam_Logo3.png",
    prefijoIdioma: "SP",
		descripcionIdioma: "ESPAÑOL",
		url: "https://www.latamairlines.com/pe/es",
		categoria: "plata",
	},
	{
		idSponsor: "7",
		nombre: "Cerro Verde",
		image: "/img/logo_cerro_verde 1.png",
    prefijoIdioma: "SP",
		descripcionIdioma: "ESPAÑOL",
		url: "https://cerroverdemirador.com/",
		categoria: "agradecimiento",
	},
	{
		idSponsor: "8",
		nombre: "Southern",
		image: "/img/Southern_logo 1.png",
    prefijoIdioma: "SP",
		descripcionIdioma: "ESPAÑOL",
		url: "https://southerncoppercorp.com/",
		categoria: "cobre",
	},
];
export default mockSponsors;
